import '@radix-ui/themes/styles.css';
import './theme-config.css'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Container, Theme, ThemePanel} from '@radix-ui/themes'
import NavBar from './navBar'
import AuthProvider from './Auth/provider';

const inter = Inter({ subsets: ['latin'],
variable: '--font-inter' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AuthProvider>
      <body className={inter.variable}>
        <Theme accentColor="blue" radius="large">
        <NavBar/>
        <main className='p-5'>
          <Container>
          {children}
          </Container>
          </main>
        </Theme>
      </body>
      </AuthProvider>
    </html>
  )
}

// bg-[#120627]